# Generated by Django 4.0.4 on 2022-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slide_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slide_img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bedroom_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
