# Generated by Django 4.0.4 on 2022-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bedroom2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='bedroom3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='bedroom4_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
