# Generated by Django 4.0.4 on 2022-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0003_home_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='gallery2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='gallery3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='gallery4_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='gallery5_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
