# Generated by Django 4.0.4 on 2022-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0004_home_gallery2_image_home_gallery3_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='arrival',
            field=models.CharField(default='DEFAULT VALUE', max_length=300),
        ),
        migrations.AddField(
            model_name='home',
            name='departure',
            field=models.TextField(default='DEFAULT VALUE', max_length=1000),
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=300),
        ),
        migrations.AddField(
            model_name='home',
            name='rooms',
            field=models.CharField(default='DEFAULT VALUE', max_length=500),
        ),
    ]
