# Generated by Django 4.0.4 on 2022-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0005_contact_home_arrival_home_departure_home_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.TextField(default='DEFAULT VALUE', max_length=1000)),
                ('arrival', models.CharField(default='DEFAULT VALUE', max_length=300)),
                ('email', models.CharField(default='DEFAULT VALUE', max_length=300)),
                ('rooms', models.CharField(default='DEFAULT VALUE', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='home',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='home',
            name='email',
        ),
        migrations.RemoveField(
            model_name='home',
            name='rooms',
        ),
    ]
