# Generated by Django 4.0.4 on 2022-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0006_bookings_remove_home_arrival_remove_home_departure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default='DEFAULT VALUE', max_length=1000),
        ),
    ]
