# Generated by Django 4.0.4 on 2022-05-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0007_remove_contact_name_contact_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
