# Generated by Django 4.0.4 on 2022-05-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0009_alter_contact_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacting',
        ),
    ]
