# Generated by Django 4.0.4 on 2022-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0011_rename_bookings_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='arrival',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='booked',
            name='departure',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='booked',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='booked',
            name='rooms',
            field=models.CharField(max_length=500),
        ),
    ]
