# Generated by Django 4.0.4 on 2022-05-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0013_alter_booked_arrival_alter_booked_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
